swagger: "2.0"
info:
  title: Buyers paths
  version: 0.0.1
paths:
  /v1/loans:
    post:
      tags:
        - Loans
      summary: Create a new loan
      description: Create a new loan
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: Loan to create
          required: true
          schema:
            $ref: "#/definitions/Loan"
      responses:
        '200':
          description: Loan created
          schema:
            $ref: "#/definitions/Loan"
        '400':
          description: Invalid loan
          schema:
            $ref: "#/definitions/ErrorAPI"
        '500':
          description: Internal server error
          schema:
            $ref: "#/definitions/ErrorAPI"


definitions:
  Loan:
    type: object
    properties:
      borrower_id:
        type: integer 
  ErrorAPI:
    type: object
    properties:
      message:
        type: string
      err_code:
        type: string
        